
import java.sql.Connection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
import java.sql.*;
public class Order extends javax.swing.JFrame {
        public static int price=0;
    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCheckBox1.setText("Cappuchino");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(40, 60, 160, 30);

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCheckBox2.setText("Latte");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(40, 180, 110, 30);

        jCheckBox3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCheckBox3.setText("Black coffee");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(40, 100, 160, 30);

        jCheckBox4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCheckBox4.setText("Espresso");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(40, 140, 120, 37);

        jCheckBox5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jCheckBox5.setText("Soy Milk Coffee");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(40, 30, 200, 20);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(260, 20, 40, 30);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(260, 60, 40, 30);
        getContentPane().add(jSpinner3);
        jSpinner3.setBounds(260, 100, 40, 30);
        getContentPane().add(jSpinner4);
        jSpinner4.setBounds(260, 140, 40, 30);
        getContentPane().add(jSpinner5);
        jSpinner5.setBounds(260, 180, 40, 30);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 220, 80, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 270, 70, 20);

        jButton2.setText("Proceed to Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 260, 129, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Total Amount");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 260, 150, 28);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\coffe_chocolate_texture1504.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-1230, -270, 1670, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{  
Class.forName("com.mysql.jdbc.Driver");  
Connection con=DriverManager.getConnection(  
"jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false","root","srishti8*"  );  
Statement stmt=con.createStatement();  
ResultSet rs=stmt.executeQuery("select * from coffeemenu");
int k=0,c=1;
while(rs.next()) 
{
    if(jCheckBox5.isSelected() && c==1){
        k=rs.getInt(4);
    price= price+(k * (int)jSpinner1.getValue());
    }
   if(jCheckBox1.isSelected() && c==2){
        k=rs.getInt(4);
    price= price+(k * (int)jSpinner2.getValue());
    }
       
    if(jCheckBox3.isSelected() && c==3){
        k=rs.getInt(4);
    price= price+(k * (int)jSpinner3.getValue());
    }
        
   if(jCheckBox4.isSelected() && c==4){
        k=rs.getInt(4);
    price= price+(k * (int)jSpinner4.getValue());
    }
       
   if(jCheckBox2.isSelected() && c==5){
        k=rs.getInt(4);
    price= price+(k * (int)jSpinner5.getValue());
    }
   c++;
       
} 
 jLabel1.setText(String.valueOf(price));
 price=0;

con.close();  
}catch(Exception e){ System.out.println(e);}  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if (evt.getActionCommand().equals("Proceed to Payment"))
    { this.setVisible(false);
      new Payment().setVisible(true);// TODO add your handling code here:
    }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    // End of variables declaration//GEN-END:variables
}
